TMF3/TMF

addons/spectator/functions/fn_escmenuHandler.sqf

functions of scroll-wheel and shift changed, "U" wasn't in the list.

Edit escmenu text

---

addons/spectator/functions/fn_drawTags.sqf

Sometimes the tags for vehicles would not render when they should have. This fixes the issue.

Spectator - Fix vehicle draw tags check

---

addons/spectator/XEH_postInit.sqf
addons/spectator/functions/fn_drawTags.sqf
addons/spectator/functions/fn_init.sqf
addons/spectator/functions/fn_keyhandler.sqf
addons/spectator/functions/fn_onLoad.sqf
addons/spectator/functions/fn_perFrameHandler.sqf
addons/spectator/functions/fn_updateGroupCache.sqf
addons/spectator/functions/fn_zeusUnload.sqf

*This pull request does the following:*
- Adds to the work in #66 - Adding further redundancy if the spectator group can not be created or the group disappears. Disables the ST HUD while spectator is open.
- Speed improvements to `tmf_spectator_fnc_drawTags` in test case ~8.3ms to 6.26ms (~34 to 39 frames)
- On exiting and opening Zeus the position is kept between Zeus and Spectator.

Spectator Improvements

---

addons/spectator/functions/fn_drawTags.sqf
addons/spectator/functions/fn_escmenuHandler.sqf
addons/spectator/functions/fn_handleUnitList.sqf
addons/spectator/functions/fn_init.sqf
addons/spectator/functions/fn_keyhandler.sqf
addons/spectator/functions/fn_menuHandler.sqf
addons/spectator/functions/fn_perFrameHandler.sqf

- Fix #91
- Smooths transition from freecam to followcam
- Gives all admins (1Tac admin) access to debug console in spectator
- Makes the control garbage collector run 3x faster

Fix tags for players and disable cinema borders

---

addons/autotest/functions/fn_testGear.sqf

issue: Autotest craps out when checking hmd[] in loadouts

fix for issue #105

---

addons/acre2/Cfg3DEN.hpp
addons/acre2/XEH_postInit.sqf
addons/common/XEH_postInit.sqf

**What this pull request does:**
- ACRE2 and ST HUD now use [CBA settings](https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System) for setting various options. This pull request removes their handling from TMF with the intent that they are set via CBA settings system. For sever wide settings use a custom addon like this -> https://github.com/Sniperhid/1tac_misc/pull/63
- Removes the following ACRE2 settings from TMF
- Addresses #69 and #94

Address mod options that now use CBA Settings.

---

addons/acre2/functions/fn_createPresets.sqf

- In ACRE2 version 2.4.1 the hash type changed this fixes it.

Fix ACRE2 hashes switch to new hash type.

---

addons/ai/modules/waveSpawner.hpp
addons/spectator/CfgVehicles.hpp
addons/spectator/config.cpp

```
19:38:50 File x\tmf\addons\ai\modules\waveSpawner.hpp, line 29: '/CfgVehicles/TMF_ai_wavespawn/Arguments/Delay.description': Missing ';' at the end of line
19:38:50 File x\tmf\addons\spectator\CfgVehicles.hpp, line 83: '/CfgVehicles/TMF_spectator_unit.scopeCurator': Missing ';' at the end of line
19:38:50 File x\tmf\addons\spectator\config.cpp, line 59: '/RscTitles/TMF_spectator_escDisplay/controls/Text.font': Missing ';' at the end of line
19:38:50 File x\tmf\addons\spectator\config.cpp, line 71: '/RscTitles/TMF_spectator_escDisplay/controls/MissionHeader.font': Missing ';' at the end of line
```
Fix the warnings in the RPT

Fix RPT warnings

---

addons/common/functions/fn_initDisplayMultiplayerSetup.sqf

- Fix issue #129 ensuring that every slot description has at least one word remaining.

Improve slot screen group names

---

addons/ai/functions/fn_hunt.sqf

- Allows AI in hunt module to go upstairs. AI path-finding can still be a bit wonky with mission maker placed buildings but this certainly lowers the prospects of some players from camping.

Fix Hunt Module - Remove Dalek mode AI can now go upstairs.

---

addons/common/display3DEN.hpp

`20:04:33 Updating base class Separator1->ctrlStatic, by x\tmf\addons\common\config.bin/display3DEN/Controls/Toolbar/Controls/Separator3/ (original a3\3den\config.bin)`

Fix updating base class RPT spam

---

addons/common/functions/fn_initDisplayMultiplayerSetup.sqf

Essentially issues would crop up where some slots wouldn't show if a particularly naming method was used. This PR also fully ensures that no slot will have an empty slot description cementing the fix for #129 
**Bugged:**
**Fixed:**

Fix slot description renaming where some slots wouldn't show

---

addons/orbat/functions/fn_setup.sqf

This handles the case where a side/faction doesn't have a root node defined in the ORBAT tree. Usually an indicator that the mission wasn't made from a valid template.

ORBAT: Handle missing parts of the ORBAT array.

---

addons/orbat/XEH_postInit.sqf

Sometimes  group names are incorrect on the orbat page. This is because `GroupID` won't return the correct group name. This PR increases the delay in the aim of reducing its occurance.

Increase time before ORBAT briefing page appears.

---

addons/ai/functions/fn_garrisonQuantity.sqf
addons/ai/functions/fn_spawnWave.sqf

- The version of `createUnit` we use does not set the side of the unit. Details in this ticket -> https://feedback.bistudio.com/T70739.
- This PR ensures that their side is set correctly. Resolves #166

Ensure side of spawned units is correct.

---

addons/acre2/functions/fn_clientInit.sqf

- Fixes a bug where the `radios` field would be ignored in mission loadouts.
- When the mission CfgLoadouts spec was updated I forgot to update the lookup here.

Fix - 'radios' field in assignGear being ignored

---

addons/spectator/functions/fn_init.sqf

- Addresses #19 
- In short if you JIPed and your unit died whilst JIPing or the unit had switch groups spectator wouldn't load properly because of weird engine behaviour. This fixes it.

Fix spectator JIP issues.

---

addons/ai/functions/fn_spawnWave.sqf

- Fix #177
- All groups start with a move waypoint to the spawn location.
- When creating groups/units via script command this first waypoint is [0,0,0]
- When using `createWaypoint` with the index it attempts to insert the waypoint at the specified index. What was occurring was that this [0,0,0] waypoint would be bumped to the end of the array of waypoints as each waypoint was added to the unit. This ensures that the first waypoint is not overriden.

Fix wave spawner giving extra waypoint.

---

addons/safestart/functions/fn_briefingTextLoad.sqf

- Adds more of a delay of showing the safestart cuontdown in the briefing. As it would sometimes prematurely run the checks and thus not display. Should be sufficient delay to function.
- Fix #183

Fix safestart briefing display

---

addons/acre2/XEH_postInit.sqf
addons/briefing/XEH_postInit.sqf
addons/common/XEH_postInit.sqf
addons/orbat/XEH_postInit.sqf

- Some systems (ACRE2/ORBAT markers) and briefing pages require variables to be sent to clients before they are executed.
- In theory this PR now sends a variable late in the initialization that should be sent last and then makes the clients wait for it. So in theory these variables should be initialized before things continue.
- Should fix #173 and #111

Wait for variables to be sent.

---

addons/common/functions/fn_numToColor.sqf
addons/orbat/Cfg3DEN.hpp
addons/orbat/CfgFunctions.hpp
addons/orbat/functions/fn_createBriefingPage.sqf
addons/orbat/functions/fn_loadTeams.sqf
addons/orbat/functions/fn_setup.sqf
addons/orbat/ui_scripts/GroupMarker.sqf
addons/orbat/ui_scripts/OrbatSettings.sqf

- Allows adding vehicles to ORBAT
- They can have map markers with callsign shown
- They will show on briefing screen
- Vehicles will be given a Vehicle number if no callsign is given. The briefing page now has an indictator of vehicle uniqueness so that it is easy to distinguish if 1 or 2 vehicles of the same type (i.e. M113) are being used by different groups.
- Vehicles now show a single fraction showing how many seats have been occupied versus total which is clearer to a player (shown above).
- Address #46 
** Changes for mission maker **
- Add Vehicle to ORBAT system (from vehicle attributes):
- Vehicles can be moved around as per other nodes in the ORBAT system

Add Vehicles to ORBAT system.

---

addons/acre2/XEH_postInit.sqf

- Previously you would have to run custom Radio networks for the babel settings to be enforced.
- This allows Babel system to be used without custom radio networks

Allow Babel settings to function if not using radio networks

---

addons/common/CfgEventHandlers.hpp
addons/common/CfgFunctions.hpp
addons/common/functions/fn_initDisplayDebriefing.sqf

- Adds ability to override text on the animated end mission page (previously ending text had to be declared in mission config). This will be handy for the TMF admin menu.
- Example:
Execute following code
```sqf
tmf_common_EndMissionText = ["Bear","Powered by Snippers Industries"];
["END1"] spawn BIS_fnc_endMission;
```
Example end mission page:

Allow setting custom text on the animated mission outro.

---

addons/briefing/ui_scripts/BriefingSettings.sqf

- Fix for units not always appearing in Briefing Screen #221

Fix some units not appearing in briefing menu in eden

---

addons/briefing/functions/fn_unitPage.sqf

Now displays
- Role from assigngear component
- Types of magazines given, instead of just e.g. [6+1] count after weapon name
- Uniform and vest (previously only backpack)
- Total weight (if ACE3 is loaded)

Enhance equipment briefing page

---

addons/ai/CfgEventHandlers.hpp
addons/ai/XEH_postInit.sqf
addons/ai/config.cpp
addons/ai/functions/fn_garrison.sqf
addons/ai/functions/fn_garrisonQuantity.sqf

**What this pull request does**
- EnableAI/DisableAI effects do not broadcast. This is problem when AI are transfered particularly when garrisioned, as they may abandon their posts. This didn't happen all the time.
- For Garrison only this will set the AI flags when unit ownership is transfered (event driven).

Sort out Garrison on Headless Clients

---

addons/ai/functions/fn_spawnWave.sqf
addons/ai/functions/fn_waveInit.sqf
addons/spectator/functions/fn_createGroupControl.sqf
addons/spectator/functions/fn_keyhandler.sqf

Rewrite of the wave spawner.
- Rewrote most code regarding building the wave data structure into a more sane layout
- Enable the groups inside vehicles to remain independent, an example to task them to get out and perform actions.
- Fix for annoying issue where "asd" would be displayed under a units group marker.
- Added output to the tracers keybind to indicate on and off.
The only problem is that this might cause issues to some missions where the previous wrong behaviour where all units inside a vehicle would be merged into one group will now correctly be separate groups.
I don't think this is very likely to occur frequently.
[video showcase](https://youtu.be/IyuXtf67A9o)

Rewrite wavespawner + minor fixes

---

addons/assigngear/XEH_preStart.sqf

Fixes bug/oversight where (for example) the american and russian facesets don't include the faces from their parent class (caucasian)

Include parent class faces in facesets

---

addons/safestart/CfgModules.hpp
addons/safestart/functions/fn_moduleInit.sqf

As the time control can not be set to less than 0, then time 0 should mean infinite safestart.

Tweak safestart module

---

addons/adminmenu/functions/fnc_endMission_sideSpecificLocal.sqf
addons/spectator/config.cpp

Makes fnc_sideSpecificLocal check stored spectator data for player side, as playerSide returns sideLogic.

Side specific endmission spectator fix

---

addons/acre2/XEH_PREP.sqf
addons/acre2/autotest.hpp
addons/acre2/config.cpp
addons/acre2/functions/fnc_testBabel.sqf
addons/acre2/functions/fnc_testNets.sqf
addons/assigngear/XEH_PREP.sqf
addons/assigngear/autotest.hpp
addons/assigngear/config.cpp
addons/assigngear/functions/fnc_testGear.sqf
addons/autotest/XEH_PREP.sqf
addons/autotest/XEH_preStart.sqf
addons/autotest/autotest.hpp
addons/autotest/config.cpp
addons/autotest/functions/fnc_autotest.sqf
addons/autotest/functions/fnc_testAI.sqf
addons/autotest/functions/fnc_testDLC.sqf
addons/autotest/functions/fnc_testEndings.sqf
addons/autotest/functions/fnc_testGroups.sqf
addons/autotest/functions/fnc_testHCs.sqf
addons/common/functions/fnc_evaluateCondArray.sqf
addons/spectator/XEH_PREP.sqf
addons/spectator/autotest.hpp
addons/spectator/config.cpp
addons/spectator/functions/fnc_testSpectator.sqf

* Test for unmentioned DLC usage (vehicles and player units)
* Test for number of HCs, and if they're correctly set up.
* Test babel
* Test radio network assignment
---
Additionally all autotests were moved from `fnc_autotest` to config, and to separate components.  
Warning amounts are now also pulled from autotest config.

New tests for Autotest

---

addons/adminmenu/functions/fnc_isAuthorized.sqf
addons/adminmenu/functions/fnc_keyPressed.sqf

Executing it without parameters caused errors in some circumstances

Fixed adminmenu error
