TMF3/TMF

addons/briefing/CfgDiary.hpp

Make briefing panel wider still

---

addons/assigngear/CfgLoadouts.hpp

Capitalization

---

addons/spectator/functions/fn_drawMap.sqf
addons/spectator/functions/fn_drawTags.sqf
addons/spectator/functions/fn_init.sqf
addons/spectator/functions/fn_perFrameHandler.sqf

* Fixed tracers acting funny on the map
* Fixed deathtags displaying names for non players
* Added small icon to denote the group leader
* Changed icon for vehicle to a box
* Disabled the ACE damage, better to rely on our own here i think.
Fixes #32,#34

* Fixed nametags not showing names for players

---

addons/common/functions/fn_endMission.sqf

OCAP 10 second timeout

---

addons/assigngear/Cfg3DEN.hpp
addons/assigngear/CfgFunctions.hpp
addons/assigngear/functions/fn_onEdenMessageRecieved.sqf
addons/assigngear/functions/fn_onEdenMissionChange.sqf

As requested, also has a handy different notification:

Re-apply TMF gear on mission save (if description.ext has changed)

---

README.md

Addresses the briefing not showing up on dedicated servers.

Update readme.md - Add a common issues section

---

addons/respawn/functions/fn_handleRespawnUI.sqf

Should lower the amount mistakes that can be made and help speed things up!

Respawn - Retain previous state of controls, show playercounts for side/faction

---

addons/common/functions/fn_isAdmin.sqf

This should prevent the bug where sometimes in spectator one can not access the admin tool.

Update Admin Check for new version of 1Tac admin

---

addons/common/CfgFunctions.hpp
addons/common/functions/fn_getPosVisual.sqf
addons/spectator/functions/fn_drawTags.sqf
addons/spectator/functions/fn_init.sqf
addons/spectator/functions/fn_keyhandler.sqf
addons/spectator/functions/fn_onScreen.sqf
addons/spectator/functions/fn_perFrameHandler.sqf
addons/spectator/functions/fn_updateGroupCache.sqf
addons/spectator/functions/fn_zeusUnload.sqf

Fixes #71 
Also fixes issue with groupicons and unit tags sticking too close to the ground.

Fixes #71 and some issues with tags height

---

addons/orbat/functions/fn_setup.sqf

ORBAT: Fix disabling the map markers still shows ORBAT briefing page.

---

addons/common/XEH_postInit.sqf
addons/orbat/XEH_postInit.sqf

- Faster updating of FT markers.
- Replace one PFH with a wait and execute

Minor cleanup and optimise

---

addons/ai/functions/fn_spawnWave.sqf
addons/ai/functions/fn_waveInit.sqf

Fixes not being able to put units in the air and as well fixes direction not being accounted for.
not tested..

Fixes not being able to put units in the air and as well fixes direction not being accounted for.

---

addons/assigngear/CfgLoadouts.hpp
addons/assigngear/functions/fn_loadFactions.sqf
addons/assigngear/functions/fn_loadRoles.sqf

It should be noted these are completely optional and are not necessary in any manner. As requested by @beaar

Assign Gear - In eden add tooltips for factions and roles.

---

addons/spectator/XEH_postInit.sqf
addons/spectator/functions/fn_init.sqf

Create a spectator group for spectator to avoid hitting the sideLogic group limit.

---

addons/assigngear/functions/fn_onEdenMessageRecieved.sqf
addons/common/display3DEN.hpp
addons/main/config.cpp
addons/orbat/Cfg3DEN.hpp
addons/spectator/config.cpp
addons/teleport/config.cpp

many instances of ambiguous "Teamwork" changed to "TMF", some other minor stuff

typography stuff

---

addons/spectator/functions/fn_init.sqf
addons/spectator/functions/fn_perFrameHandler.sqf

- Have the control garbage collector delete controls for dead units.
- Killfeed - show the vehicle type if a passenger makes a kill.

Spectator minor improvements

---

addons/ai/functions/fn_addWaveHandler.sqf

addWaveHandler function

---

addons/common/Cfg3DEN.hpp
addons/common/CfgEventHandlers.hpp
addons/common/CfgFunctions.hpp
addons/common/CfgVehicles.hpp
addons/common/config.cpp
addons/common/functions/fn_edenDraw.sqf
addons/common/functions/fn_edenHideMapObjects.sqf
addons/common/functions/fn_edenInit.sqf
addons/common/functions/fn_hideMapObjectsInit.sqf

3 orthagonal lines are checked, extending 2m from the origin in both directions. All map objects intersecting these lines are cut off.

Adds a logic object to hide map objects at game start

---

addons/autotest/functions/fn_testGear.sqf

This time I made sure to clean my local branches first. Sorry 'bout that.

fix for issue #105 without a typo (CfgWeapons) 

---

addons/orbat/CfgEventHandlers.hpp
addons/orbat/XEH_postInit.sqf

- Fixes the GPS displays
- Update to use the display load event in CBA and remove old method.

Fix GPS with sensor update

---

addons/ai/functions/fn_spawnWave.sqf
addons/autotest/functions/fn_autotest.sqf
addons/autotest/functions/fn_testGear.sqf

- Increase group limit in autotest
- Make gear testing run a bit faster
- Wavespawner groups will now clean themselves up.

Misc minor improvements

---

addons/ai/functions/fn_waveInit.sqf
addons/ai/modules/waveSpawner.hpp

Added delay to wave spawner and some minor tweaks.

---

addons/spectator/functions/fn_toggleUI.sqf

Hide chat when spectator ui is hidden

---

addons/ai/functions/fn_garrisonQuantity.sqf

- Fixes script error if insufficient free garrison positions are available. Also adds a marker to assist the mission maker in resolving the issue.

Minor garrison module fix

---

addons/ai/modules/garrison.hpp

Fixes issue https://github.com/TMF3/TMF/issues/140

fix wrong scope in Garrison (Legacy) module

---

addons/autotest/functions/fn_testGear.sqf

for this issue https://github.com/TMF3/TMF/issues/142

fixes "fixed" autotest, again

---

addons/ai/functions/fn_addWaveHandler.sqf

- Fixes `TMF_ai_fnc_addWaveHandler` previously would error out.

Fix TMF_ai_fnc_addWavehandler

---

addons/zeus/$PBOPREFIX$
addons/zeus/CfgEventHandlers.hpp
addons/zeus/CfgFunctions.hpp
addons/zeus/RscDisplayCurator.hpp
addons/zeus/config.cpp
addons/zeus/functions/fn_openedZeus.sqf
addons/zeus/functions/fn_openedZeusServer.sqf
addons/zeus/functions/fn_toggleAllStaticsZeus.sqf
addons/zeus/functions/fn_toggleAllStaticsZeusServer.sqf
addons/zeus/functions/fn_toggleAllUnitsZeus.sqf
addons/zeus/functions/fn_toggleAllUnitsZeusServer.sqf
addons/zeus/script_component.hpp

**What this pull request does:**
- Add a bottom bar to the Zeus interface
- Add toggle-able buttons for what units should editable in Zeus. (Another step towards moving away from 1Tac admin).

Add zeus button bar

---

addons/briefing/CfgDiary.hpp
addons/common/functions/fn_hideMapObjectsInit.sqf

* Fixes hiding map objects after a recent arma update
* Fixes briefing being very / too wide

Fixes to my components

---

addons/common/CfgFunctions.hpp
addons/common/functions/fn_secondsToTime.sqf
addons/spectator/functions/fn_keyhandler.sqf

Press P to show time in the chat.

#155 show time in spectator

---

addons/spectator/functions/fn_init.sqf

Implemented variables acording to #144

---

addons/orbat/functions/fn_createBriefingPage.sqf
addons/orbat/functions/fn_setup.sqf

- Fixes a rare case where sometimes groups are missing markers and also are missing from the briefing orbat page.

Handle orphaned groups and units.

---

addons/ai/functions/fn_spawnWave.sqf

Fixes issue with helicopters/planes starting with engines off.
Fixes #167

Fixes issue with helicopters/planes

---

addons/acre2/XEH_postInit.sqf
addons/acre2/functions/fn_createPresets.sqf

Fix AN/PRC-77 Support and remove ACRE script error.

---

addons/acre2/CfgFunctions.hpp
addons/acre2/functions/fn_edenUnitToRadios.sqf
addons/assigngear/functions/fn_addBackpackItems.sqf
addons/autotest/functions/fn_testGear.sqf

Autotest - Test if items actually fit in the inventory.

---

addons/adminmenu/functions/fn_zeusServerMake.sqf
addons/spectator/XEH_postInit.sqf
addons/zeus/RscDisplayCurator.hpp

- Fix spectator disconnect error on server
- Fix enum error on creating zeus entity.
- Correct tooltip type and missing semicolons in zeus part

Minor fixes to Zeus system. Clean up RPT. Fix spectator disconnect cleanup.

---

addons/common/display3DEN.hpp
addons/common/functions/fn_edenInit.sqf

Reset state of garrison toggle button on missionload (amongst other codes).

---

addons/acre2/CfgFunctions.hpp
addons/acre2/functions/fn_edenUnitToRadios.sqf
addons/acre2/functions/fn_unitToPreset.sqf
addons/acre2/ui_scripts/RadioChannels.sqf

- Fixes #184 
- Adds a function for determining a unit's radio preset.

ACRE2 - Handle removing channels properly

---

addons/common/CfgFunctions.hpp
addons/common/functions/fn_edenDisplayFactionIcons.sqf
addons/common/functions/fn_edenInit.sqf

Display faction icons in 3DEN asset lists

---

addons/ai/functions/fn_spawnWave.sqf
addons/ai/functions/fn_waveInit.sqf

Make the wave spawner support the vehicle customization

---

addons/acre2/ui_scripts/BabelSettings.sqf
addons/acre2/ui_scripts/RadioChannels.sqf

Fix ACRE2 EDEN UI script errors.

---

addons/autotest/functions/fn_testGear.sqf

AutoTest: Add checking for goggles config for backpackItems

---

addons/briefing/Cfg3DEN.hpp
addons/briefing/ui_scripts/BriefingSettings.sqf
addons/common/functions/fn_sideToString.sqf
addons/common/functions/fn_sideToTexture.sqf

- Adds SideLogic playable virtual entities to the briefing UI tool > 
- Addresses #215

Allow sideLogic units (virtual entities) to have briefings.

---

addons/autotest/Cfg3DEN.hpp

Fixes RPT errors
`Error in bin\config.bin/Cfg3DEN/Mission/<tag>/AttributeCategories/<tag>/Attributes/<attribute>.condition`
Same as https://github.com/Theseus-Aegis/Mods/pull/366 (used by permission), just contributing back. :)

Fix Eden Attribute condition RPT error

---

addons/ai/functions/fn_garrisonQuantity.sqf
addons/ai/modules/garrison.hpp

- The template AI for the garrison module will be removed at game start - AI will only spawn when trigger runs (if a trigger is present) otherwise instantly
- Address #236

Update AI Garrison Module store AI until trigger is fired.

---

addons/acre2/Cfg3DEN.hpp
addons/briefing/Cfg3DEN.hpp
addons/common/Cfg3DEN.hpp
addons/orbat/Cfg3DEN.hpp
addons/spectator/Cfg3DEN.hpp

- Fix #240 - Removes attribute condition RPT spam

Fix condition RPT spam

---

addons/autotest/functions/fn_testGear.sqf

CBA_fnc_compatibleMagazines from CBA 3.9.0

Magazine well support in autotest

---

addons/assigngear/CfgFunctions.hpp
addons/assigngear/functions/fn_assignGear.sqf
addons/assigngear/functions/fn_setInsignia.sqf
addons/assigngear/loadouts/blu_f.hpp
addons/assigngear/loadouts/civ_f.hpp
addons/assigngear/loadouts/fia_f.hpp
addons/assigngear/loadouts/ind_f.hpp
addons/assigngear/loadouts/opf_f.hpp
addons/autotest/functions/fn_testGear.sqf

Essentially an edited version of TMF_assignGear_fnc_setFace

Added insignias to assignGear

---

addons/adminmenu/functions/fn_utility_quickRespawn_local.sqf

Tweaks quick respawn
- Renable vanilla radio channels (map markers/and text chat)
- Run ACRE2 code to set languages etc. (Also will safely remove from ACRE spectator system)
- Refresh ORBAT markers
- Create briefing page

Improve Quick Respawn

---

addons/briefing/functions/fn_unitPage.sqf
addons/briefing/functions/fn_vehiclePage.sqf

Improve equipment briefing for vehicles, units with UGLs

---

addons/orbat/XEH_postInit.sqf

*What this pull request does*
- Fixes the `WaitUntil` bug introduced with more stringent checks with Contact DLC arma 3 patch.

Fix Tao folding map WaitUntil

---

addons/common/CfgEventHandlers.hpp

I don't think this belongs in TMF and definitely not in common

Remove allowCrewInImmobile init EH

---

addons/adminmenu/XEH_postInit.sqf
addons/adminmenu/functions/fn_dashboard.sqf
addons/adminmenu/functions/fn_fpsHandlerServer.sqf
addons/adminmenu/gui/dashboard.hpp

**What This Pull Request does**
- Shows the number of groups local to Server/Headless clients

Display Headless info in the admin menu

---

addons/adminmenu/CfgFunctions.hpp
addons/adminmenu/functions/fn_remoteControl.sqf
addons/adminmenu/functions/fn_remoteControl_dialog.sqf
addons/adminmenu/gui/adminMenu.hpp

Adds a modal window when activating remote control on a vehicle from spectator, letting you select a specific crew member

Spectator Remote Control modal

---

addons/adminmenu/CfgFunctions.hpp
addons/adminmenu/functions/fn_adminEye_draw.sqf
addons/adminmenu/functions/fn_adminEye_onClick.sqf
addons/adminmenu/functions/fn_adminEye_onKeyPress.sqf
addons/adminmenu/functions/fn_adminEye_open.sqf
addons/adminmenu/functions/fn_adminEye_restoreTrigger.sqf
addons/adminmenu/gui/adminMenu.hpp

**What this pull request does**
- Displays more information about triggers 
- Allows Triggers and wave spawners to be selected (more info) - Light up red on selected - Can use T key to trigger the wave spawner/trigger. This could be used to trigger wave spawners again.

Enhance AdminEye

---

addons/autotest/functions/fn_testGear.sqf

Resolves https://github.com/TMF3/TMF/issues/280

Accept glasses in items[]

---

addons/spectator/CfgFunctions.hpp
addons/spectator/functions/fn_drawGroupMarker.sqf
addons/spectator/functions/fn_drawMap.sqf
addons/spectator/functions/fn_drawUnitMarker.sqf
addons/spectator/functions/fn_drawVehicleMarker.sqf
addons/spectator/functions/fn_keyhandler.sqf
addons/spectator/functions/fn_updateKillList.sqf
addons/spectator/script_component.hpp

Rewrite for clarity
Solves an issue with units appearing as vehicles.

Fixes a few bugs with the map rendering in spectator

---

addons/acre2/XEH_postInit.sqf
addons/acre2/functions/fn_clientInit.sqf
addons/acre2/functions/fn_createPresets.sqf

**What this pull request does**
- Prevent radios being duplicated for JIPs
- Minor cleanup of acre component for newer array commands

Prevent radio duplication for JIPs

---

addons/autotest/functions/fn_testGear.sqf

Added role to the output string for missing radio.

Tweak to testGear

---

addons/assigngear/functions/fn_assignGear.sqf

Fix addGoggles empty string

---

addons/assigngear/CfgEventHandlers.hpp
addons/assigngear/CfgFunctions.hpp
addons/assigngear/XEH_postInit.sqf
addons/assigngear/functions/fn_assignGear.sqf
addons/assigngear/functions/fn_loadAssignGear.sqf
addons/assigngear/functions/fn_overrideProfileItems.sqf
addons/assigngear/functions/fn_setFace.sqf
addons/assigngear/functions/fn_setGoggles.sqf

Loadout faces and goggles should now apply after player profile

Delay AssignGear faces+goggles

---

addons/ai/functions/fn_spawnWave.sqf

 Fixes #318

---

addons/ai/functions/fn_spawnWave.sqf
addons/ai/functions/fn_waveInit.sqf
addons/ai/script_component.hpp

Useful for garrisoned units and the like.

Preserve disableAI on wavespawn

---

addons/autotest/functions/fnc_autotest.sqf
addons/autotest/functions/fnc_testGear.sqf

Fix autotest silencer check

---

addons/adminmenu/XEH_postInit.sqf
addons/adminmenu/functions/fnc_utility_heal.sqf

Fixed error on mission end

---

addons/safestart/functions/pfh_exit.sqf
addons/safestart/functions/pfh_start.sqf

fixes initialization order issue with ACE throwing, and also adds handling for changing setting during safestart

Fix ACE throwing on mission start

---

addons/assigngear/Cfg3DEN.hpp
addons/assigngear/XEH_preInit.sqf

PREP appears to run after 3DEN event handlers. Moved to preInit.

Fixed assigngear when opening editor

---

addons/spectator/XEH_clientPostInit.sqf
addons/spectator/XEH_postInit.sqf

Fix JIP to AI slots

---

addons/spectator/CfgEventHandlers.hpp
addons/spectator/CfgVehicles.hpp
addons/spectator/XEH_PREP.sqf
addons/spectator/XEH_clientPostInit.sqf
addons/spectator/functions/fnc_initSpectatorUnit.sqf

Add placeable Spectator unit

---

addons/ai/functions/fnc_garrisonQuantity.sqf
addons/ai/modules/garrison.hpp

[Video](https://www.youtube.com/watch?v=AYksyN9hPlI)

Adds wake up function to garrison module
